import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import apiClient from '../features/auth/infrastructure/http/apiClient';
import type { Order, OrderStatus } from './orderTypes';

const currency = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);
const statusLabels: Record<OrderStatus, string> = { CREATED: 'Creada', IN_PREPARATION: 'En preparación', READY: 'Lista', DELIVERED: 'Entregada', CANCELLED: 'Cancelada' };
const serviceLabels = { DINE_IN: 'Para comer aquí', TAKEAWAY: 'Para llevar', DELIVERY: 'Domicilio' };
const visibleNumber = (value: number) => String(value).padStart(5, '0');
const nextStatus: Partial<Record<OrderStatus, { status: OrderStatus; label: string }>> = { CREATED: { status: 'IN_PREPARATION', label: 'Enviar a preparación' }, IN_PREPARATION: { status: 'READY', label: 'Marcar lista' }, READY: { status: 'DELIVERED', label: 'Marcar entregada' } };

export function OrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [status, setStatus] = useState<'ALL' | OrderStatus>('ALL');
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function loadOrders() {
    try { setOrders((await apiClient.get<Order[]>('/v1/orders')).data); }
    catch (requestError) { setError(axios.isAxiosError(requestError) ? requestError.response?.data?.message ?? 'No fue posible cargar las órdenes.' : 'No fue posible cargar las órdenes.'); }
  }
  useEffect(() => { void loadOrders(); }, []);
  const filteredOrders = useMemo(() => status === 'ALL' ? orders : orders.filter((order) => order.status === status), [orders, status]);

  async function changeStatus(order: Order, newStatus: OrderStatus) {
    try {
      const updated = (await apiClient.put<Order>(`/v1/orders/${order.id}/status`, { status: newStatus })).data;
      setOrders((current) => current.map((item) => item.id === order.id ? updated : item));
      setSelectedOrder((current) => current?.id === order.id ? updated : current);
    } catch (requestError) { setError(axios.isAxiosError(requestError) ? requestError.response?.data?.message ?? 'No fue posible cambiar el estado.' : 'No fue posible cambiar el estado.'); }
  }

  return <section className="min-h-screen bg-[var(--color-background)] p-4 text-[var(--color-text)] sm:p-5 lg:p-8">
    <div className="screen-only">
      <header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.35em] text-[var(--color-primary)]">Operación</p><h1 className="text-3xl font-semibold text-white sm:text-4xl">Órdenes</h1><p className="mt-2 text-sm text-[var(--color-muted)]">Consulta, prepara e imprime los pedidos del establecimiento.</p></div><a href="/orders" className="rounded-xl bg-[var(--color-primary)] px-4 py-2.5 text-center text-sm font-semibold text-black">Nueva orden</a></header>
      {error ? <p className="mb-5 rounded-xl border border-rose-400/30 bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p> : null}
      <div className="mb-5 flex gap-2 overflow-x-auto pb-1"><button type="button" onClick={() => setStatus('ALL')} className={`shrink-0 rounded-xl px-4 py-2 text-sm ${status === 'ALL' ? 'bg-[var(--color-primary)] font-semibold text-black' : 'border border-[var(--color-border)] text-[var(--color-muted)]'}`}>Todas ({orders.length})</button>{(['CREATED', 'IN_PREPARATION', 'READY', 'DELIVERED', 'CANCELLED'] as OrderStatus[]).map((value) => <button type="button" key={value} onClick={() => setStatus(value)} className={`shrink-0 rounded-xl px-4 py-2 text-sm ${status === value ? 'bg-[var(--color-primary)] font-semibold text-black' : 'border border-[var(--color-border)] text-[var(--color-muted)]'}`}>{statusLabels[value]}</button>)}</div>
      <div className="space-y-3">{filteredOrders.length ? filteredOrders.map((order) => <article key={order.id} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-card-bg)] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-white">Orden #{visibleNumber(order.order_number)}</h2><span className="rounded-full border border-[var(--color-border)] px-2 py-1 text-xs text-[var(--color-primary)]">{statusLabels[order.status]}</span></div><p className="mt-1 text-sm text-[var(--color-muted)]">{serviceLabels[order.service_type]}{order.table_name ? ` · ${order.table_name}` : ''}{order.customer_name ? ` · ${order.customer_name}` : ''}</p></div><div className="flex flex-wrap items-center justify-end gap-2"><p className="mr-2 text-lg font-semibold text-white">{currency(order.total)}</p>{nextStatus[order.status] ? <button type="button" onClick={() => void changeStatus(order, nextStatus[order.status]!.status)} className="rounded-xl bg-[var(--color-primary)] px-3 py-2 text-sm font-semibold text-black">{nextStatus[order.status]!.label}</button> : null}<button type="button" onClick={() => setSelectedOrder(order)} className="rounded-xl border border-[var(--color-border)] px-3 py-2 text-sm text-[var(--color-primary)]">Ver e imprimir</button></div></div><p className="mt-3 text-xs text-[var(--color-muted)]">{order.items.reduce((sum, item) => sum + item.quantity, 0)} productos · {new Date(order.created_at).toLocaleString('es-CO')}</p></article>) : <div className="rounded-2xl border border-dashed border-[var(--color-border)] p-10 text-center text-sm text-[var(--color-muted)]">No hay órdenes para este filtro.</div>}</div>
    </div>
    {selectedOrder ? <div className="screen-only fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="max-h-[90dvh] w-full max-w-lg overflow-y-auto rounded-2xl border border-[var(--color-border)] bg-[var(--color-card-bg)] p-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-[var(--color-primary)]">{selectedOrder.tenant_name}</p><h2 className="mt-1 text-2xl font-semibold text-white">Orden #{visibleNumber(selectedOrder.order_number)}</h2><p className="mt-1 text-sm text-[var(--color-muted)]">{selectedOrder.location_name ?? 'Sede no asignada'}</p><p className="mt-1 text-sm text-[var(--color-muted)]">Estado: {statusLabels[selectedOrder.status]}</p></div><button type="button" onClick={() => setSelectedOrder(null)} aria-label="Cerrar detalle" className="text-2xl text-[var(--color-muted)]">×</button></div><div className="mt-5 space-y-3">{selectedOrder.items.map((item) => <div key={item.id} className="border-b border-[var(--color-border)] pb-3"><div className="flex justify-between gap-3 text-sm text-white"><span>{item.quantity} × {item.product_name}</span><span>{currency(item.subtotal)}</span></div>{item.modifiers.length ? <p className="mt-1 text-xs text-[var(--color-muted)]">{item.modifiers.map((option) => option.name).join(', ')}</p> : null}{item.toppings.length ? <p className="mt-1 text-xs text-[var(--color-muted)]">Adicionales: {item.toppings.map((option) => option.name).join(', ')}</p> : null}{item.notes ? <p className="mt-1 text-xs italic text-[var(--color-muted)]">{item.notes}</p> : null}</div>)}</div><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between text-[var(--color-muted)]"><span>Subtotal</span><span>{currency(selectedOrder.subtotal)}</span></div><div className="flex justify-between text-[var(--color-muted)]"><span>Impuestos</span><span>{currency(selectedOrder.tax)}</span></div><div className="flex justify-between text-lg font-semibold text-white"><span>Total</span><span>{currency(selectedOrder.total)}</span></div></div><div className="mt-5 flex flex-wrap gap-2">{nextStatus[selectedOrder.status] ? <button type="button" onClick={() => void changeStatus(selectedOrder, nextStatus[selectedOrder.status]!.status)} className="flex-1 rounded-xl bg-[var(--color-primary)] px-4 py-3 text-sm font-semibold text-black">{nextStatus[selectedOrder.status]!.label}</button> : null}<button type="button" onClick={() => window.print()} className="flex-1 rounded-xl border border-[var(--color-border)] px-4 py-3 text-sm font-semibold text-white">Imprimir orden</button></div></div></div> : null}
    {selectedOrder ? <div className="print-only print-ticket"><h1>{selectedOrder.tenant_name}</h1><h2>Sede: {selectedOrder.location_name ?? 'Sede no asignada'}</h2><h2>Orden #{visibleNumber(selectedOrder.order_number)}</h2><p>{new Date(selectedOrder.created_at).toLocaleString('es-CO')}</p><p>{serviceLabels[selectedOrder.service_type]}{selectedOrder.table_name ? ` · ${selectedOrder.table_name}` : ''}</p><hr />{selectedOrder.items.map((item) => <div key={item.id}><p><strong>{item.quantity} × {item.product_name}</strong><span>{currency(item.subtotal)}</span></p>{item.modifiers.map((option) => <small key={option.id}>+ {option.name}</small>)}{item.toppings.map((option) => <small key={option.id}>+ {option.name}</small>)}{item.notes ? <small>{item.notes}</small> : null}</div>)}<hr /><p><span>Subtotal</span><span>{currency(selectedOrder.subtotal)}</span></p><p><span>Impuestos</span><span>{currency(selectedOrder.tax)}</span></p><p><strong>Total</strong><strong>{currency(selectedOrder.total)}</strong></p></div> : null}
  </section>;
}
